services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: convertor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/convertor
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FLYWAY_PLACEHOLDERS_ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
      spring.flyway.placeholders.admin_password_hash: ${ADMIN_PASSWORD_HASH}
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: