spring.datasource.url=jdbc:postgresql://localhost:5432/convertor
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

convector.nbrb.url=https://api.nbrb.by/

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.example=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n

spring.jpa.show-sql=true

nbrb.converter.shedulers.cron=0 0 0 * * *

resilience4j.circuitbreaker.instances.nbrbApi.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.nbrbApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.nbrbApi.failure-rate-threshold=80
resilience4j.circuitbreaker.instances.nbrbApi.wait-duration-in-open-state=120s
resilience4j.circuitbreaker.instances.nbrbApi.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.nbrbApi.minimum-number-of-calls=2

springdoc.swagger-ui.csrf.enabled=false
springdoc.api-docs.enabled=true

jwt.secret=${SECRET}
jwt.expiration=36000

spring.flyway.placeholders.admin_username=admin
spring.flyway.placeholders.admin_password_hash=${ADMIN_PASSWORD}